-- 1. Create the Database
CREATE DATABASE IF NOT EXISTS blog_db;

-- 2. Select the Database to use
USE blog_db;

-- 3. Create the 'users' table (For Login)
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(50) NOT NULL
);

-- 4. Create the 'posts' table (For Blog Data)
CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    author VARCHAR(50),
    likes INT DEFAULT 0
);

-- 5. Insert the Admin User (With your specific password)
-- "IGNORE" ensures it doesn't crash if the user already exists
INSERT IGNORE INTO users (username, password) VALUES ('admin', 'Ayushdada123');

-- 6. Insert a standard user for testing
INSERT IGNORE INTO users (username, password) VALUES ('guest', '12345');

-- 7. (Optional) Insert some dummy posts so the Feed isn't empty
INSERT INTO posts (title, content, author, likes) VALUES 
('Welcome to Java Blog', 'This is the first post generated by SQL code.', 'admin', 10),
('JDBC is Powerful', 'Connecting Java to MySQL allows for persistent data storage.', 'guest', 5);

-- 8. Check if everything worked
SELECT * FROM users;
SELECT * FROM posts;